### PR TITLE
Design… by twitter. 

### PR DESCRIPTION
**Pull request by mycrobe**
Relatively reactive search interface with working style for:

* Text search
* Filter
* Suggestions

It's partially placeholders, and partially wired up but broken because @ajo2995 turned off CORS on data.gramene.org in his recent upgrade to SOLR 5.2

### CODE REVIEW

**Comment by mycrobe** [comment]
I turned off most of the tests since I refactored the layout so much. Sorry.

**Comment by mycrobe** [comment]
I should note that we compile bootstrap from its .less sourcefiles with our own .less styles. This means that I can use the same variables as them for sizes rather than introducing a bunch of constants into our own style code.

**Comment by ajo2995** [comment]
Can you check that you can use data.gramene.org now? I didn't turn off CORS, just messed up the rewriteRule.

**Comment by mycrobe** [comment]
Confirmed working

**Pull request merged**
